---
- name: Get cluster pull secret
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    api_version: v1
    kind: Secret
    name: pull-secret
    namespace: openshift-config
  register: cluster_pull_secret

- name: Create pull secret in namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cluster-pull-secret
        namespace: "{{ target_namespace }}"
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ cluster_pull_secret.resources[0].data['.dockerconfigjson'] }}"

- name: Get default service account
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    api_version: v1
    kind: ServiceAccount
    name: default
    namespace: "{{ target_namespace }}"
  register: default_sa

- name: Link pull secret to default service account
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    merge_type: strategic-merge
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: default
        namespace: "{{ target_namespace }}"
      imagePullSecrets: >-
        {{ default_sa.resources[0].imagePullSecrets | default([])
           | union([{'name': 'cluster-pull-secret'}]) }}
